name: CustomKits
version: 1.0.0
main: me.stakexmc.customkits.CustomKits
author: StakexMC
description: Crea Kits personalizados para tu servidor
commands:
    kits:
        usage: /<command>
        aliases: [opt]
        description: SuperLobby